version: "3.8"

services:
  db:
    image: postgres:15
    container_name: leaving-work-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: leaving_work
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data: